### ISSUE TITLE
Go: int--9223372036854776000 fixture

### ISSUE THREAD

**Issue by vmx** [ipld/codec-fixtures#39]
I wonder why the `int--9223372036854776000` test fixture is passing on Go. It is not marked for being skipped. `-9223372036854776000` is out of range of an int64, so I'd expect an error.

**Comment by rvagg** [comment]
OK, I have the answer!

The fixture is actually for `-9223372036854775808` which is the minimum int64; I believe that's why I selected that value. _But_, it's out of the safe range for JavaScript so my guess is that the test fixture _name_ got "fixed" with some script I wrote to assemble all of these:

```
$ node -e "console.log(-9223372036854775808, '(🍾)')"
-9223372036854776000 (🍾)
```

But the fixture is for `-9223372036854775808`:

```
$ curl -Ls https://raw.githubusercontent.com/ipld/codec-fixtures/master/fixtures/int--9223372036854776000/bafyreidh4mvwi7pnv62beigtnibakkxpsgjzua5g7kdvu2deltah6kigay.dag-cbor | cborg bin2diag
3b 7fffffffffffffff                               # negint(-9223372036854775808)
```

```
$ curl -Ls https://raw.githubusercontent.com/ipld/codec-fixtures/master/fixtures/int--9223372036854776000/baguqeeraqu4gi57tv5d6jiftbdxdwotirxyw5czcfaif3v6u3tkcvgahzn4a.dag-json
-9223372036854775808
```


I think the fix here is to just rename the fixture.

**Comment by vmx** [comment]
Thanks! I should've checked what the file actually contains. I saw a failure on a Rust CBOR implementation (I currently only have this locally), which failed on that test. So I guess that implementation really has a bug, as Rust certainly [should also support `-9223372036854775808`](https://doc.rust-lang.org/std/primitive.i64.html#associatedconstant.MIN). Though that's a completely different issue.
