### ISSUE TITLE
Testing current versions

### ISSUE THREAD

**Issue by vmx** [ipld/codec-fixtures#50]
The CI is bit confusing. Currently we test JS, Go and Rust with their master branches. We don't test JS and Rust with their released versions. That only happens with the Go versions.

I'm not sure if the automated CI is a good fit, given that this is a cross language repo. Anyway, I suggest that we also have a job that runs JS and Rust on the released version.

**Comment by rvagg** [comment]
mm, we could remove the unified-ci (protocol/.github) stuff from here, I mainly added it because it has some really nice linting and comprehensive testing for the Go code but aside from that it's not useful. The Cron workflow does most of the interesting work for pull requests and cron jobs and uses latest of all the things.

The JS versions get tested with their latest **released** version (not master): https://github.com/ipld/codec-fixtures/blob/master/.github/workflows/cron.yml, but in that case we have auto-releases on almost every commit that happens to the repo so the difference with any `master` version is minimal.

For the Go we use `@master` of go-ipld-prime because tagging happens much less frequently with Go and it's entirely possible that breaking changes get introduced in those repos long before a release is cut. I don't do the same for go-codec-dagpb in cron.yml though, maybe I should, but I've also introduced the unified-ci stuff over there and plan to do much more frequent tagging of any changes that happen there too.

For Rust, that's really your call and depends on how you expect users to consume the libraries and what kind of signal you want. If you want the assurance that whatever you have on master is stable then you may as well do that here. If you want the delayed indication after a release then that's your call. You're also welcome to add both; maybe extend cron.yml to add a "Rust (released)"?.

**Comment by vmx** [comment]
> You're also welcome to add both; maybe extend cron.yml to add a "Rust (released)"?.

I'll do that. I think it's good to test on master, so that one gets an early signal if something breaks.
